<?php


$title = 'Add new Address';
$this->headTitle($title);
?>

<h1><?php echo $this->escapeHtml($title)?></h1>
<?php
$brokerForm = $this->brokerForm;
$addressForm = $this->addressForm;
$addressForm->setAttribute('action', $this->url('broker', array('action' => 'add')));

$addressForm->prepare();
?>

<?php // if (isset($this->error)) { print_r($this->error); } ?>


<?php echo $this->form()->openTag($addressForm); ?>
<?php echo $this->formRow($addressForm->get('csrf')); ?>
<div >
<h2>Broker</h2>


<?php echo $this->formRow($brokerForm->get('is_application_owner')); ?>

<?php echo $this->formRow($brokerForm->get('broker_name')); ?>

<?php echo $this->formRow($brokerForm->get('email')); ?>

<?php echo $this->formRow($brokerForm->get('phone')); ?>

<?php echo $this->formRow($brokerForm->get('mobile')); ?>

<?php echo $this->formRow($brokerForm->get('fax')); ?>



<h2>address</h2>
<?php echo $this->formRow($addressForm->get('longitude')); ?>

<?php echo $this->formRow($addressForm->get('latitude')); ?>

<?php echo $this->formRow($addressForm->get('street')); ?>

<?php echo $this->formRow($addressForm->get('housenr')); ?>

<?php echo $this->formRow($addressForm->get('housenr_ext')); ?>

<?php echo $this->formRow($addressForm->get('postalcode')); ?>

<?php echo $this->formRow($addressForm->get('city')); ?>

<?php echo $this->formRow($addressForm->get('state')); ?>
<input type="submit">
<?php echo $this->form()->closeTag(); ?>


</div>