<?php
use Zend\View\Helper\EscapeHtml;

$title = 'Add new Address';
$this->headTitle($title);
?>

<h1><?php echo $this->escapeHtml($title)?></h1>
<?php
$addressForm = $this->addressForm;
$addressForm->setAttribute('action', $this->url('broker', array('action' => 'test')));
$addressForm->prepare();
?>

<?php if (isset($this->error)) { print_r($this->error); } ?>


<?php echo $this->form()->openTag($addressForm); ?>
<div >


<?php echo $this->formRow($addressForm->get('longitude')); ?>

<?php echo $this->formRow($addressForm->get('latitude')); ?>

<?php echo $this->formRow($addressForm->get('street')); ?>

<?php echo $this->formRow($addressForm->get('housenr')); ?>

<?php echo $this->formRow($addressForm->get('housenr_ext')); ?>

<?php echo $this->formRow($addressForm->get('postalcode')); ?>

<?php echo $this->formRow($addressForm->get('city')); ?>

<?php echo $this->formRow($addressForm->get('state')); ?>
<input type="submit">
<?php echo $this->form()->closeTag($addressForm); ?>


</div>