<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'WwtgRealEstate\Module'                        => __DIR__ . '/Module.php',
    'WwtgRealEstate\Controller\ResidentController' => __DIR__ . '/src/WwtgRealEstate/Controller/ResidentController.php',
    'WwtgRealEstateTest\Framework\TestCase'        => __DIR__ . '/tests/WwtgRealEstate/Framework/TestCase.php',
    'WwtgRealEstateTest\SampleTest'                => __DIR__ . '/tests/WwtgRealEstate/SampleTest.php',
);